// <auto-generated />
namespace MiAre_TestProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.0-preview2-24180-01")]
    public sealed partial class SecondCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202405311433506_SecondCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
